---
title: "Taller 4."
author: "Alejandro Bedoya Taborda\nAngie Melissa Montoya Urrego\nCristian Camilo Henao Rojas\nMariana Arias Montoya\nLuis Felipe Marin Buitrago"
date: "17/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```


```{r}
#lectura de la base de datos.
encuesta_habitos <- read.csv2("Encuesta_habitos.csv", 
                       encoding = "UTF-8",
                       dec = ".")
```

# Genero

#### Tabla de frecuencia.
```{r}
#tabla de frecuencias de género.
genero <- table(encuesta_habitos$genero)
genero
genero_porcentaje <- round(genero / sum(genero)*100,2)
```

#### Grafica.
```{r}

#Trabajamos el lienzo
par(mar = c(8, 5, 3, 3))# le damos margenes

plot(seq(0,3,length.out = 100), 1:100, 
     type = "n",
     main = "Genero",
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3)

g1 <- barplot(genero_porcentaje,
        col = c("#d9ae94", "#f1dca7"),
        cex.names = 0.65,
        las=1,
        add = TRUE,
)

text(g1, c(30,78), 
     labels = paste(formatC(genero_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```
# Fecha de nacimiento {.tabset}
## Gráfica
```{r}
library(knitr)
encuesta<-read.csv2("Encuesta_habitos.csv", 
                       encoding = "UTF-8",
                       dec = ".")
fechas<- as.Date(encuesta$fecha_dep,"%d/%m/%Y")
fec_table<-table(format(fechas,"%Y"))
e<-kable(fec_table, col.names = c('Año','Frecuencia'), align = 'lc')
library(ggplot2)
ggplot(encuesta, aes(x=seq(0,100,length.out = 132),y=as.numeric(format(fechas,"%Y")))) + 
    geom_boxplot(fill="slateblue", alpha=0.4) + theme_bw()+
    xlab("")+ylab('Año')+ggtitle('Boxplot de la variable Años')+theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (20),hjust = .5)) + coord_cartesian(ylim = c(1956,2020)) + scale_y_continuous(breaks = seq(1950,2020,5)) + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(),axis.title.y = element_text(size = 15, vjust = 1.3), axis.text.y = element_text(family = "Helvetica", face = "bold", size = (10)))

 ggplot(encuesta, aes(x=seq(0,100,length.out = 132),y=as.numeric(format(fechas,"%Y")))) + 
    geom_violin(fill="slateblue", alpha=0.4) + theme_bw()+
    xlab("")+ylab('Año')+ggtitle('Violín de la variable Años')+theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (20),hjust = .5)) + coord_cartesian(ylim = c(1956,2020)) + scale_y_continuous(breaks = seq(1950,2020,5)) + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(),axis.title.y = element_text(size = 15, vjust = 1.3), axis.text.y = element_text(family = "Helvetica", face = "bold", size = (10)))

```


## Resumen numerico

```{r}
summary(as.numeric(format(fechas,"%Y")))
```

## Tabla de frecuencia
```{r}
e
```

## Grafica Dias
```{r}
dtable<- format(fechas,'%d')
dias<- as.vector(table(dtable))
dias<-append(dias,0,after = 2)
df<- data.frame('dias'= dias)
dtable1<-sort(unique(c(dtable,'03')))
ggplot(df,aes(x=dtable1,y=dias))+geom_segment(aes(x=dtable1,xend=dtable1,y=0,yend=dias), color='grey70',lwd=1)+theme_light() + scale_y_continuous(breaks = seq(0,15,1))+ggtitle('Lollipop de la variable Días' ) +
  theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (20),hjust = .5),axis.title.x = element_text( size = (15)), axis.text.y = element_text(family = "Helvetica", face = "bold", size = (10)),axis.text.x = element_text(family = "Helvetica", face = "bold", size = (10)),axis.title.y = element_text(size = 15),panel.grid.major.x = element_blank(),panel.border = element_blank(),axis.ticks.x = element_blank())+ylab('Número de personas')+ xlab('Día de cumpleaños' )+ geom_point(color="brown", size=3)
```

# Edad {.tabset}

## Grafica

```{r}
fechadepu<- fechas
fechadepu<-fechadepu[!format(fechadepu,"%Y") %in% as.character(seq(2005,2020,1))]



edad<-round(as.numeric(Sys.Date() - fechadepu )/ 365,0)
ggplot(as.data.frame(edad), aes(x=seq(0,100,length.out = 125),y=edad)) + 
    geom_boxplot(fill="darkorange", alpha=0.4) + theme_grey()+
    xlab("")+ylab('Años')+ggtitle('Boxplot de la Edad')+theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (20),hjust = .5)) + coord_cartesian(ylim = c(15,70)) +scale_y_continuous(breaks = seq(15,70,5)) + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(),axis.title.y = element_text(size = 15, vjust = 1.3), axis.text.y = element_text(family = "Helvetica", face = "bold", size = (10)))

ggplot(as.data.frame(edad), aes(x=seq(0,100,length.out = 125),y=edad)) + 
    geom_violin(fill="darkorange", alpha=0.4) + theme_grey()+
    xlab("")+ylab('Años')+ggtitle('Violín de la Edad')+theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (20),hjust = .5)) + coord_cartesian(ylim = c(15,70)) + scale_y_continuous(breaks = seq(15,70,5)) + theme(axis.text.x = element_blank(),axis.ticks.x = element_blank(),axis.title.y = element_text(size = 15, vjust = 1.3), axis.text.y = element_text(family = "Helvetica", face = "bold", size = (10)))

```

## Resumen numérico
```{r}

summary(edad)
 
```


# Carrera

```{r}
carrera <- table(encuesta_habitos$carrera_dep)
carrera
carrera_porcentaje <- round(carrera/sum(carrera) * 100,2)
```


```{r}

#Trabajamos el lienzo
par(mar = c(10, 8, 3, 3))# le damos margenes

plot(seq(0,10,length.out = 100), 1:100, 
     type = "n",
     main = "Carrera",
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3)

g2 <- barplot(carrera_porcentaje,
        col = c("#d9ae94", "#f1dca7"),
        las=1,
        names.arg = "",
        add = TRUE,
)

text(g2, c(60,10,8,8,45,10,10,8), 
     labels = paste(formatC(carrera_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

text(g2 + 0.2,
    par("usr") [3], 0.4,
    labels = names(carrera),
    srt = 45,
    pos = 2,
    cex = 0.60,
    xpd = TRUE)

```

# PAPA {.tabset}
## Grafica
```{r}
p<- sort(encuesta$PAPA)
frecpapa<-as.vector(table(p))
p<-unique(p)
dfpapa<- data.frame(papa=p,frecuencia=frecpapa)
ggplot(encuesta, aes(encuesta$PAPA))+ geom_freqpoly(bins=20,color='mediumvioletred',lwd=1)+ ggtitle('Polígono de Frecuencia del PAPA')+ scale_y_continuous(breaks = seq(0,20,2)) + ylab('Frecuencia')+xlab('P.A.P.A')+ theme(plot.title = element_text(family = "Helvetica", face = "bold", size = (20),hjust = .5))+ theme(axis.ticks.x = element_blank(),axis.text.x = element_text(family = "Helvetica", face = "bold", size = (10)),axis.text.y = element_text(family = "Helvetica", face = "bold", size = (10)), axis.title.x = element_text(size = 15),axis.title.y = element_text(size = 15))
```


## Tabla de Frecuencia
```{r}
kable(table(encuesta$PAPA), col.names = c('PAPA','Frecuencia'), align = 'cc')
```

# Estrato

```{r}
estrato <- table(encuesta_habitos$estrato)
estrato
estrato_porcentaje <- round(estrato/sum(estrato)*100,2)

```


```{r}

#Trabajamos el lienzo
par(mar = c(8, 5, 3, 3))# le damos margenes

plot(seq(0,7,length.out = 100), 1:100, 
     type = "n",
     main = "Estrato",
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3)

g1 <- barplot(estrato_porcentaje,
        col = c("#d9ae94", "#f1dca7"),
        cex.names = 0.65,
        las=1,
        add = TRUE,
)

text(g1, c(8,20,40,50,12,8), 
     labels = paste(formatC(estrato_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```

# Computador de mesa:

```{r}
computador_mesa <- table(encuesta_habitos$computador_mesa)
computador_mesa
computador_mesa_porcentaje <- round(computador_mesa/sum(computador_mesa)*100,2)
```

```{r}

#Trabajamos el lienzo
par(mar = c(8, 5, 3, 3))# le damos margenes

plot(seq(0,5,length.out = 100), 1:100, 
     type = "n",
     main = "Computador de mesa",
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3)

g1 <- barplot(computador_mesa_porcentaje,
        col = c("#d9ae94", "#f1dca7"),
        cex.names = 0.65,
        las=1,
        add = TRUE,
)

text(g1, c(75,8,8,35), 
     labels = paste(formatC(computador_mesa_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```

# Portatil


```{r}
portatil <- table(encuesta_habitos$portatil)
portatil
portatil_porcentaje <- round(portatil/sum(portatil)*100,2)
```

```{r}

#Trabajamos el lienzo
par(mar = c(8, 5, 3, 3))# le damos margenes

plot(seq(0,5,length.out = 100), 1:100, 
     type = "n",
     main = "Portatil",
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3)

g1 <- barplot(portatil_porcentaje,
        col = c("#d9ae94", "#f1dca7"),
        cex.names = 0.65,
        las=1,
        add = TRUE,
)

text(g1, c(18,8,16,78), 
     labels = paste(formatC(portatil_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```


# Internet

```{r}
internet <- table(encuesta_habitos$internet)
internet
internet_porcentaje <- round(internet/sum(internet)*100,2)
```

```{r}

#Trabajamos el lienzo
par(mar = c(8, 5, 3, 3))# le damos margenes

plot(seq(0,7,length.out = 100), 1:100,
     type = "n",
     main = "Internet",
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3) # las lineas que señalan las gráficas.

g1 <- barplot(internet_porcentaje,
        col = c("#d9ae94", "#f1dca7"), #Colores de la gráfica
        cex.names = 0.65,#tamaño del nombre
        las=1, #Posición de los nombres
        add = TRUE, # se agrega para poder poner encima de un plot.
)
# Con las siguientes líneas se trabajan los porcentajes encima de la barra.

text(g1, c(10,8,10,10,38,60), #Aquí pueden modificar las alturas.
     labels = paste(formatC(internet_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```

# Smartphone


```{r}
smartphone <- table(encuesta_habitos$smartphone)
smartphone
smartphone_porcentaje <- round(smartphone/sum(smartphone)*100,2)

```



```{r}

#Trabajamos el lienzo
par(mar = c(5, 5, 3, 3))# le damos margenes

plot(seq(0,5,length.out = 100), 1:100,
     type = "n",
     main = "Smartphone", 
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3) # las lineas que señalan las gráficas.

g1 <- barplot(smartphone_porcentaje,
        col = c("#d9ae94", "#f1dca7"), #Colores de la gráfica
        cex.names = 0.65,#tamaño del nombre
        las=1, #Posición de los nombres
        add = TRUE, # se agrega para poder poner encima de un plot.
)
# Con las siguientes líneas se trabajan los porcentajes encima de la barra.

text(g1, c(6,6,10,102), #Aquí pueden modificar las alturas.
     labels = paste(formatC(smartphone_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```

# Estadisticas gov

```{r}
gobierno <- table(encuesta_habitos$estad_gov)
gobierno

```

```{r}
gobierno_porcentaje <- round(gobierno/sum(gobierno)*100,2)
gobierno_porcentaje
```

```{r}

#Trabajamos el lienzo
par(mar = c(5, 5, 3, 3))# le damos margenes

plot(seq(0,5,length.out = 100), 1:100,
     type = "n",
     main = "Estadistica del gobierno.", 
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3) # las lineas que señalan las gráficas.

g1 <- barplot(gobierno_porcentaje,
        col = c("#d9ae94", "#f1dca7"), #Colores de la gráfica
        cex.names = 0.65,#tamaño del nombre
        las=1, #Posición de los nombres
        add = TRUE, # se agrega para poder poner encima de un plot.
)
# Con las siguientes líneas se trabajan los porcentajes encima de la barra.

text(g1, c(78,30), #Aquí pueden modificar las alturas.
     labels = paste(formatC(gobierno_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```

# Habitos de estudio(PENDIENTE):

# Número aleatorio.

```{r}
aleatorio <- table(encuesta_habitos$aleatorio)
aleatorio
```

```{r}
aleatorio_porcentaje <- round(aleatorio/sum(aleatorio)*100,2)
aleatorio_porcentaje
```

```{r}
#Trabajamos el lienzo
par(mar = c(5, 5, 3, 3))# le damos margenes

plot(seq(0,13,length.out = 100), 1:100,
     type = "n",
     main = "Número aleatorio", 
     cex.main = 0.75,
     axes = FALSE,
     xlab = "",
     ylab = "Porcentajes"
     )

abline(h = seq(0,100,10), col = "gray", lty = 3) # las lineas que señalan las gráficas.

g1 <- barplot(aleatorio_porcentaje,
        col = c("#d9ae94", "#f1dca7"), #Colores de la gráfica
        cex.names = 0.60,#tamaño del nombre
        las=1, #Posición de los nombres
        add = TRUE, # se agrega para poder poner encima de un plot.
)
# Con las siguientes líneas se trabajan los porcentajes encima de la barra.

text(g1, c(8,10,12,10,4,14,16,10,30,18,10), #Aquí pueden modificar las alturas.
     labels = paste(formatC(aleatorio_porcentaje,
                            digits = 6, decimal.mark = ",", 
                            big.mark = "."), "%"))

```



